[font]
normal = { family = "ZedMono Nerd Font", style = "Extended Bold" }
bold = { family = "ZedMono Nerd Font", style = "Extended Bold" }
italic = { family = "ZedMono Nerd Font", style = "Extended Bold" }
bold_italic = { family = "ZedMono Nerd Font", style = "Extended Bold" }
size = 10.2

[env]
term = "xterm-256color"

[window]
opacity = 1
#blur = true

# Default colors
[colors.primary]
background = '#232a2e'
foreground = '#d3c6aa'

# Cursor colors
# [colors.cursor]
# cursor = '#d3c6aa'
# text = '#d3c6aa'

# Normal colors
[colors.normal]
black = '#7a8478'
blue = '#7fbbb3'
cyan = '#83c092'
green = '#a7c080'
magenta = '#d699b6'
red = '#e67e80'
white = '#d3c6aa'
yellow = '#dbbc7f'

# Bright colors
[colors.bright]
black = '#7a8478'
blue = '#7fbbb3'
cyan = '#83c092'
green = '#a7c080'
magenta = '#d699b6'
red = '#e67e80'
white = '#d3c6aa'
yellow = '#dbbc7f'

# Selection colors
#[colors.selection]
#background = '#dae9f9'
#text = '#000000'
